# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m9U7nM-fczeRNh6SDp0sDmN6Q1X_ZdTF
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline





data = pd.read_csv('/content/dataset.csv').rename(columns=str.lower)
data.head(3)

data.info()

print('Dataset comprises of {} observations and {} characteristics'.format(data.shape[0],data.shape[1]))
print('\nUnique Values: ',data.nunique())
print('\nMissing Values: ',data.isna().sum())

data.describe().T

len(data['year'].unique()), data['year'].min(), data['year'].max()

data = data.fillna(0)

data.hist(figsize=(14,10),color='blue');

plt.style.use('fivethirtyeight')
data.groupby('year')['annual'].mean().plot(title='Annual Rainfall Of The 117 Years ',
                                          figsize=(13,8),
                                          c='g',
                                          marker='s')
plt.ylabel('Rainfalls (mm)');

data.drop('annual',axis=1).groupby('year').mean().T.plot(title='Monthly  Rainfall of The 117 Years',figsize=(12,7),alpha=.15,legend=False);